#!/usr/bin/env python3
"""
render-override.py — profile + config 를 읽어 docker-compose.override.yaml 을 생성.

입력:
  - profiles.yaml 의 llamacpp/<profile> (CONFIG_NAME, MODEL_FILE 등)
  - config/llamacpp/<CONFIG_NAME>.yaml  (llama-server 플래그)

출력:
  - docker-compose.override.yaml  (services.llama-server.command 블록)

사용:
  python3 scripts/llamacpp/render-override.py <profile-name>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = ROOT / "config" / "llamacpp"
COMPOSE_DIR = ROOT / "compose" / "llamacpp"
RUNTIME_DIR = ROOT / ".runtime" / "llamacpp"

sys.path.insert(0, str(ROOT))
from tui.common import profile_store  # noqa: E402

_SAFE_NAME = re.compile(r"^[a-z0-9][a-z0-9_-]*$")


def _validate_name(name: str, kind: str) -> str:
    """filename stem 과 compose project name 에 안전한 값만 허용."""
    if not name or not _SAFE_NAME.match(name) or ".." in name:
        raise SystemExit(
            f"잘못된 {kind} 이름: {name!r} (허용: 소문자, 숫자, _, -)"
        )
    return name


def parse_env_file(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        # 따옴표 제거
        value = value.strip().strip('"').strip("'")
        env[key.strip()] = value
    return env


def render_command(cfg: dict, model_file: str = "") -> list[str]:
    """config yaml → llama-server CLI 인자 리스트."""
    args: list[str] = ["--host", "0.0.0.0", "--port", "8080", "--no-webui"]

    # 특수 키 먼저 처리
    resolved_model = str(cfg.pop("model-file", "") or model_file).strip()
    if not resolved_model:
        raise ValueError("model-file missing in config and profile.model_file is empty")
    args.extend(["--model", f"/models/{resolved_model}"])

    # WebUI 는 강제 off. 사용자가 webui 활성화하려 해도 무시.
    cfg.pop("no-webui", None)
    cfg.pop("webui", None)

    override_tensors = cfg.pop("override-tensors", None) or []
    extra_args = cfg.pop("extra-args", None) or []

    for key, value in cfg.items():
        flag = f"--{key}"
        if isinstance(value, bool):
            if value:
                args.append(flag)
            # False 는 무시
        elif isinstance(value, list):
            for item in value:
                args.extend([flag, str(item)])
        elif value is None:
            continue
        else:
            args.extend([flag, str(value)])

    for pattern in override_tensors:
        args.extend(["-ot", str(pattern)])

    args.extend(str(a) for a in extra_args)
    return args


def main() -> int:
    if len(sys.argv) != 2:
        print(f"사용법: {sys.argv[0]} <profile-name>", file=sys.stderr)
        return 2

    profile = _validate_name(sys.argv[1], "profile")
    stored = profile_store.load_profile(profile, "llamacpp")
    if stored is None:
        print(f"프로필 없음: llamacpp/{profile} (profiles.yaml 확인)", file=sys.stderr)
        return 1

    config_name = _validate_name(stored.config_name or profile, "config")
    config_path = CONFIG_DIR / f"{config_name}.yaml"
    if not config_path.exists():
        print(f"config 파일 없음: {config_path}", file=sys.stderr)
        return 1

    cfg = yaml.safe_load(config_path.read_text()) or {}
    if not isinstance(cfg, dict):
        print(f"config 형식 오류: mapping YAML 이 필요합니다: {config_path}", file=sys.stderr)
        return 1
    try:
        command = render_command(cfg, stored.model_file)
    except ValueError as exc:
        print(f"config 렌더 실패: {exc}", file=sys.stderr)
        return 1

    override = {
        "services": {
            "llama-server": {
                "command": command,
            },
        },
    }

    # Per-profile override file so multiple llamacpp profiles can run
    # concurrently without clobbering each other's command.
    out_path = RUNTIME_DIR / f"override-{profile}.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# AUTO-GENERATED by scripts/llamacpp/render-override.py — 직접 수정 금지.\n"
        f"# Profile: {profile}  Config: {config_name}\n"
    )
    out_path.write_text(header + yaml.safe_dump(override, sort_keys=False, width=200))
    print(str(out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
