#!/usr/bin/env python3
"""
render-override.py — profile + config 를 읽어 docker-compose.override.yaml 을 생성.

입력:
  - profiles/<profile>.env  (CONFIG_NAME, MODEL_FILE 등)
  - config/<CONFIG_NAME>.yaml  (llama-server 플래그)

출력:
  - docker-compose.override.yaml  (services.llama-server.command 블록)

사용:
  python3 scripts/render-override.py <profile-name>
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
PROFILES_DIR = ROOT / "profiles" / "llamacpp"
CONFIG_DIR = ROOT / "config" / "llamacpp"
COMPOSE_DIR = ROOT / "compose" / "llamacpp"


def parse_env_file(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        # 따옴표 제거
        value = value.strip().strip('"').strip("'")
        env[key.strip()] = value
    return env


def render_command(cfg: dict) -> list[str]:
    """config yaml → llama-server CLI 인자 리스트."""
    args: list[str] = ["--host", "0.0.0.0", "--port", "8080"]

    # 특수 키 먼저 처리
    if "model-file" in cfg:
        args.extend(["--model", f"/models/{cfg.pop('model-file')}"])

    override_tensors = cfg.pop("override-tensors", None) or []
    extra_args = cfg.pop("extra-args", None) or []

    for key, value in cfg.items():
        flag = f"--{key}"
        if isinstance(value, bool):
            if value:
                args.append(flag)
            # False 는 무시
        elif isinstance(value, list):
            for item in value:
                args.extend([flag, str(item)])
        elif value is None:
            continue
        else:
            args.extend([flag, str(value)])

    for pattern in override_tensors:
        args.extend(["-ot", str(pattern)])

    args.extend(str(a) for a in extra_args)
    return args


def main() -> int:
    if len(sys.argv) != 2:
        print(f"사용법: {sys.argv[0]} <profile-name>", file=sys.stderr)
        return 2

    profile = sys.argv[1]
    profile_path = PROFILES_DIR / f"{profile}.env"
    if not profile_path.exists():
        print(f"프로필 파일 없음: {profile_path}", file=sys.stderr)
        return 1

    env = parse_env_file(profile_path)
    config_name = env.get("CONFIG_NAME", profile)
    config_path = CONFIG_DIR / f"{config_name}.yaml"
    if not config_path.exists():
        print(f"config 파일 없음: {config_path}", file=sys.stderr)
        return 1

    cfg = yaml.safe_load(config_path.read_text()) or {}
    command = render_command(cfg)

    override = {
        "services": {
            "llama-server": {
                "command": command,
            },
        },
    }

    out_path = COMPOSE_DIR / "docker-compose.override.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# AUTO-GENERATED by scripts/llamacpp/render-override.py — 직접 수정 금지.\n"
        f"# Profile: {profile}  Config: {config_name}\n"
    )
    out_path.write_text(header + yaml.safe_dump(override, sort_keys=False, width=200))
    print(f"✓ {out_path.relative_to(ROOT)} (profile={profile})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
