# https://docs.vllm.ai/projects/recipes/en/latest/Qwen/Qwen3-VL.html
model: Qwen/Qwen3-VL-30B-A3B-Instruct-FP8 
max-model-len: 65536
gpu-memory-utilization: 0.75
limit-mm-per-prompt.video: 0
mm-encoder-tp-mode: data
enable-request-id-headers: true
async-scheduling: true
